name: uni_links_desktop
description: A desktop (supports macOS and Windows) implementation of uni_links plugin.
version: 0.1.6
homepage: https://github.com/leanflutter/uni_links_desktop

platforms:
  macos:
  windows:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  win32_registry: 
    git:
      url: https://github.com/pavinrex/win32_registry.git

dev_dependencies:
  dependency_validator: ^3.0.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: uni_links
    platforms:
      macos:
        pluginClass: UniLinksDesktopPlugin
      windows:
        pluginClass: UniLinksDesktopPlugin
